#!/bin/bash
#SBATCH --job-name=vasp
#SBATCH --output=vasp.%j
##SBATCH --error=vasp.%j
#SBATCH --nodes=8
#SBATCH --ntasks-per-node=32
#SBATCH --time=24:00:00
#SBATCH --partition=gpuq
#SBATCH --account=gpuq
#SBATCH --dependency=afterany:286452

module load intel/impi
# module add intel/17.0.5.239 impi/2017

export OMP_NUM_THREADS=1
NCORES=$(($SLURM_NTASKS_PER_NODE * $SLURM_JOB_NUM_NODES))
MPICMD="mpirun -n $SLURM_NTASKS"  #"mpirun -genv I_MPI_FABRICS shm:ofa -n $SLURM_NTASKS"

VASPDIR="/data/groups/ping/kli103/programs/vasp/vasp.5.4.4-vtst/bin"  
#VASPDIR="/export/data/share/wufeng/programs-intel2017.5/vasp/vasp.5.4.4-vtst/bin"

echo "Start:"; date

#$MPICMD $VASPDIR/vasp_gam
$MPICMD $VASPDIR/vasp_std

echo "Done:"; date
